#!/usr/bin/env bash

set -eu

## The Godeps file is expected to have lines like so:
#
# github.com/nu7hatch/gotrail v2.6
#
## where the first element is the import path and the second is a tag
## or commit SHA in the project.

# Godeps default file is './Godeps' (can be overriden by -f)
godeps="Godeps"

# Absolute path to GPM
if [[ "$0" = /* ]]
then
  gpm=$0
else
  gpm=$(pwd)/$0
fi

## Functions

# Iterates over Godep file dependencies and sets
# the specified version on each of them.
set_dependencies() {
  while read package version url; do
    (
      install_path="${GOPATH%%:*}/src/${package%%/...}"
      [[ -e "$install_path/.git/index.lock" ]] && wait
      echo ">> Getting package "$package""

      if [[ ! -z $url ]]
      then
        git clone $url $install_path > /dev/null 2>&1
      else
        go get -u -d "$package"
      fi

      echo ">> Setting $package to version $version"
      cd $install_path
      [ -d .hg ] && hg update -q "$version"
      [ -d .git ] && git checkout -q "$version"
      [ -d .bzr ] && bzr revert -q -r "$version"

      if [[ -f "$godeps" ]]
      then
        $gpm
      fi

    ) &
  done < <(echo "$deps")
  wait
  echo ">> All Done"
}


## Main execution

# Parse command line arguemnts


while getopts “va:Hf:” OPTION
do
  case $OPTION in
    v)
      echo "v0.4.1"
      exit
      ;;
    f)
      godeps=$OPTARG
      ;;
  esac
done

# Check if Godeps file exists
if [[ ! -f "$godeps" ]]
then
  echo ">> $godeps file does not exist."
  exit 1
fi

# Get dependencies from Godeps file excluding comments
deps=$(sed 's/#.*//;/^\s*$/d' < "$godeps") || echo ""
set_dependencies
